# Regular expression variables
@{^CAPTURE}
$&; $MATCH;     ${MATCH}
$`; $PREMATCH;  ${PREMATCH}
$'; $POSTMATCH; ${POSTMATCH}
${^MATCH}
${^PREMATCH}
${^POSTMATCH}
$+; $LAST_PAREN_MATCH; ${LAST_PAREN_MATCH}
%+; %LAST_PAREN_MATCH; %{LAST_PAREN_MATCH}; %{^CAPTURE}
@+; @LAST_MATCH_END;   @{LAST_MATCH_END}
@-; @LAST_MATCH_START; @{LAST_MATCH_START}
%-; %{^CAPTURE_ALL}
$^R; $LAST_REGEXP_CODE_RESULT; ${LAST_REGEXP_CODE_RESULT}
$^N; $LAST_SUBMATCH_RESULT;    ${LAST_SUBMATCH_RESULT}
${^LAST_SUCCESSFUL_PATTERN}
${^RE_COMPILE_RECURSION_LIMIT}
${^RE_DEBUG_FLAGS}
${^RE_TRIE_MAXBUF}
